name: CI
on:
  push:
    branches:
      - master
      - main
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
  workflow_dispatch:
jobs:
  call_npm_package-build:
    uses: szikszail/workflows/.github/workflows/npm-package-build.yml@main
