# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docs

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build_and_publish_docs:
    uses: szikszail/workflows/.github/workflows/typedocs-pages.yml@main